baseURL: "https://blog.kzhrk.com/"
title: "kzhrk's blog"
paginate: 5
uglyUrls: true
enableEmoji: true
layoutDir: "layouts"
publishDir: "public"
staticDir: "static"
contentDir: "content"
metaDataFormat: "yaml"
params:
  description: "kzhrk's blog"
  keywords: "JavaScript, HTML, CSS, kzhrk"
permalinks:
  post: "/:year/:month/:title"