version: '3'
services:
  build:
    image: klakegg/hugo:0.57.2
    volumes:
      - ".:/src"
  server:
    image: klakegg/hugo:0.57.2
    command: server
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"