name: setup

runs:
  using: "composite"
  steps:
		- uses: actions/checkout@v4
		- uses: pnpm/action-setup@v4
			with:
				version: 9.4.0
		- uses: actions/setup-node@v4
			with:
				node-version: ${{ matrix.node-version }}
		- name: Install dependencies
			run: pnpm i
